// Student
const students = Array.from({ length: 801 }, (_, index) => {
  const scientistNames = [
    { first: 'Kwame', last: 'Nkrumah' },
    { first: 'Aaliyah', last: 'Smith' },
    { first: 'Chike', last: 'Okafor' },
    { first: 'Jamal', last: 'Brown' },
    { first: 'Zuri', last: 'Johnson' },
    { first: 'Adanna', last: 'Joseph' },
    { first: 'Tunde', last: 'Adeyemi' },
    { first: 'Kymani', last: 'Marley' },
    { first: 'Ngozi', last: 'Ibe' },
    { first: 'Leila', last: 'Charles' },
    { first: 'Obi', last: 'Nwankwo' },
    { first: 'Dante', last: 'Williams' },
    { first: 'Amara', last: 'Okoro' },
    { first: 'Sade', last: 'Adams' },
    { first: 'Chinua', last: 'Achebe' },
    { first: 'Rohan', last: 'Gonzalez' },
    { first: 'Kofi', last: 'Annan' },
    { first: 'Naomi', last: 'Hernandez' },
    { first: 'Dayo', last: 'Ogunleye' },
    { first: 'Tiana', last: 'Baptiste' },
    { first: 'Ahmet', last: 'Yılmaz' },
    { first: 'Fatima', last: 'Demir' },
    { first: 'Oluwaseun', last: 'Adeleke' },
    { first: 'Marley', last: 'Clarke' },
    { first: 'Efe', last: 'Okoye' },
    { first: 'Yara', last: 'Almanzar' },
    { first: 'Kwesi', last: 'Mensah' },
    { first: 'Zainab', last: 'Kaya' },
    { first: 'Olumide', last: 'Afolayan' },
    { first: 'Shevon', last: 'Persaud' },
    { first: 'Mustafa', last: 'Özdemir' },
    { first: 'Asha', last: 'Ramkissoon' },
    { first: 'Folami', last: 'Oluwole' },
    { first: 'Darnell', last: 'Facey' },
    { first: 'Ayşe', last: 'Çelik' },
    { first: 'Kwabena', last: 'Agyeman' },
    { first: 'Xiomara', last: 'Rodriguez' },
    { first: 'Chidi', last: 'Ekwueme' },
    { first: 'Esra', last: 'Yıldırım' },
    { first: 'Akin', last: 'Adebayo' },
    { first: 'Shaniqua', last: 'Thompson' },
    { first: 'Emre', last: 'Şahin' },
    { first: 'Adeola', last: 'Oladipo' },
    { first: 'Calypso', last: 'James' },
    { first: 'Oluwadamilola', last: 'Adeniyi' },
    { first: 'Zeynep', last: 'Aydın' },
    { first: 'Kwaku', last: 'Owusu' },
    { first: 'Yaritza', last: 'Diaz' },
    { first: 'Chukwuemeka', last: 'Nwosu' },
    { first: 'Mehmet', last: 'Kara' },
    { first: 'Folasade', last: 'Ogunbiyi' },
    { first: 'Delroy', last: 'Campbell' },
    { first: 'Aisha', last: 'Yılmaz' },
    { first: 'Oluwaseyi', last: 'Akinwande' },
    { first: 'Shanique', last: 'Edwards' },
    { first: 'Burak', last: 'Öztürk' },
    { first: 'Chioma', last: 'Eze' },
    { first: 'Machel', last: 'Montano' },
    { first: 'Adekunle', last: 'Adebisi' },
    { first: 'Esmeralda', last: 'Gomez' },
    { first: 'Olamide', last: 'Olatunji' },
    { first: 'Selin', last: 'Yılmaz' },
    { first: 'Kwame', last: 'Asante' },
    { first: 'Yanique', last: 'Richards' },
    { first: 'Chinedu', last: 'Onwu' },
    { first: 'Elif', last: 'Demir' },
    { first: 'Oluwadamilare', last: 'Adeyemi' },
    { first: 'Shevonne', last: 'Bacchus' },
    { first: 'Cem', last: 'Yıldız' },
    { first: 'Folake', last: 'Olawale' },
    { first: 'Usain', last: 'Bolt' },
    { first: 'Ayodeji', last: 'Balogun' },
    { first: 'Gizem', last: 'Çetin' },
    { first: 'Kwesi', last: 'Appiah' },
    { first: 'Xiomara', last: 'Fernandez' },
    { first: 'Oluwaseun', last: 'Oladele' },
    { first: 'Merve', last: 'Özdemir' },
    { first: 'Chukwudi', last: 'Okonkwo' },
    { first: 'Shantel', last: 'Williams' },
    { first: 'Emre', last: 'Kaya' },
    { first: 'Oluwadamilola', last: 'Adegoke' },
    { first: 'Yasemin', last: 'Yılmaz' },
    { first: 'Kwabena', last: 'Boateng' },
    { first: 'Yaritza', last: 'Perez' },
    { first: 'Oluwaseyi', last: 'Ogunleye' },
    { first: 'Seda', last: 'Aydın' },
    { first: 'Chidiebere', last: 'Nnamani' },
    { first: 'Shanique', last: 'Brown' },
    { first: 'Murat', last: 'Özcan' },
    { first: 'Folasade', last: 'Oluwole' },
    { first: 'Machel', last: 'Charles' },
    { first: 'Oluwadamilare', last: 'Adeyemo' },
    { first: 'Zehra', last: 'Yıldırım' },
    { first: 'Kwesi', last: 'Acheampong' },
    { first: 'Yanique', last: 'Thompson' },
    { first: 'Chukwuemeka', last: 'Okorie' },
    { first: 'Ayşe', last: 'Kaya' },
    { first: 'Oluwaseun', last: 'Oladipo' },
    { first: 'Shevon', last: 'Ramsammy' },
    { first: 'Mustafa', last: 'Çelik' },
    { first: 'Folake', last: 'Ogunbiyi' },
    { first: 'Usain', last: 'Blake' },
    { first: 'Adeola', last: 'Adeyemi' },
    { first: 'Selin', last: 'Demir' },
    { first: 'Kwame', last: 'Owusu' },
    { first: 'Xiomara', last: 'Martinez' },
    { first: 'Olumide', last: 'Oladele' },
    { first: 'Elif', last: 'Yılmaz' },
    { first: 'Chidi', last: 'Nwosu' },
    { first: 'Shaniqua', last: 'Edwards' },
    { first: 'Burak', last: 'Aydın' },
    { first: 'Oluwadamilola', last: 'Akinwande' },
    { first: 'Esra', last: 'Özdemir' },
    { first: 'Kwesi', last: 'Asante' },
    { first: 'Yaritza', last: 'Rodriguez' },
    { first: 'Chinedu', last: 'Eze' },
    { first: 'Zeynep', last: 'Kara' },
    { first: 'Oluwaseyi', last: 'Adebisi' },
    { first: 'Shevonne', last: 'Persaud' },
    { first: 'Emre', last: 'Yıldız' },
    { first: 'Folasade', last: 'Olatunji' },
    { first: 'Delroy', last: 'Thompson' },
    { first: 'Aisha', last: 'Çetin' },
    { first: 'Oluwadamilare', last: 'Olawale' },
    { first: 'Gizem', last: 'Özcan' },
    { first: 'Kwabena', last: 'Mensah' },
    { first: 'Esmeralda', last: 'Diaz' },
    { first: 'Chukwudi', last: 'Onwu' },
    { first: 'Merve', last: 'Yıldırım' },
    { first: 'Oluwaseun', last: 'Adegoke' },
    { first: 'Shanique', last: 'Campbell' },
    { first: 'Cem', last: 'Demir' },
    { first: 'Folake', last: 'Adeniyi' },
    { first: 'Machel', last: 'James' },
    { first: 'Adekunle', last: 'Ogunleye' },
    { first: 'Seda', last: 'Yılmaz' },
    { first: 'Kwesi', last: 'Boateng' },
    { first: 'Yanique', last: 'Gomez' },
    { first: 'Chidiebere', last: 'Okorie' },
    { first: 'Yasemin', last: 'Özdemir' },
    { first: 'Oluwadamilola', last: 'Oluwole' },
    { first: 'Shevon', last: 'Bacchus' },
    { first: 'Murat', last: 'Çelik' },
    { first: 'Folasade', last: 'Afolayan' },
    { first: 'Usain', last: 'Richards' },
    { first: 'Ayodeji', last: 'Oladipo' },
    { first: 'Zehra', last: 'Kaya' },
    { first: 'Kwame', last: 'Acheampong' },
    { first: 'Xiomara', last: 'Hernandez' },
    { first: 'Olumide', last: 'Adeyemo' },
    { first: 'Ayşe', last: 'Yıldız' },
    { first: 'Chidi', last: 'Nnamani' },
    { first: 'Shantel', last: 'Brown' },
    { first: 'Burak', last: 'Özcan' },
    { first: 'Oluwaseyi', last: 'Ogunbiyi' },
    { first: 'Elif', last: 'Aydın' },
    { first: 'Kwesi', last: 'Owusu' },
    { first: 'Yaritza', last: 'Fernandez' },
    { first: 'Chinedu', last: 'Okonkwo' },
    { first: 'Selin', last: 'Yıldırım' },
    { first: 'Oluwaseun', last: 'Akinwande' },
    { first: 'Shanique', last: 'Charles' },
    { first: 'Emre', last: 'Özdemir' },
    { first: 'Folake', last: 'Adebisi' },
    { first: 'Machel', last: 'Williams' },
    { first: 'Adeola', last: 'Oladele' },
    { first: 'Esra', last: 'Kara' },
    { first: 'Kwabena', last: 'Asante' },
    { first: 'Yanique', last: 'Perez' },
    { first: 'Chukwuemeka', last: 'Eze' },
    { first: 'Merve', last: 'Çetin' },
    { first: 'Oluwadamilare', last: 'Olatunji' },
    { first: 'Shevonne', last: 'Ramsammy' },
    { first: 'Mustafa', last: 'Yılmaz' },
    { first: 'Folasade', last: 'Adeyemi' },
    { first: 'Delroy', last: 'Edwards' },
    { first: 'Aisha', last: 'Özcan' },
    { first: 'Oluwaseyi', last: 'Olawale' },
    { first: 'Gizem', last: 'Demir' },
    { first: 'Kwesi', last: 'Mensah' },
    { first: 'Esmeralda', last: 'Martinez' },
    { first: 'Chidi', last: 'Onwu' },
    { first: 'Zeynep', last: 'Yıldız' },
    { first: 'Oluwadamilola', last: 'Ogunleye' },
    { first: 'Shanique', last: 'Thompson' },
    { first: 'Cem', last: 'Aydın' },
    { first: 'Folake', last: 'Adegoke' },
    { first: 'Usain', last: 'Campbell' },
    { first: 'Adekunle', last: 'Oladipo' },
    { first: 'Seda', last: 'Özdemir' },
    { first: 'Kwame', last: 'Boateng' },
    { first: 'Xiomara', last: 'Gomez' },
    { first: 'Olumide', last: 'Nwosu' },
    { first: 'Yasemin', last: 'Çelik' },
    { first: 'Chukwudi', last: 'Adeniyi' },
    { first: 'Shantel', last: 'Persaud' },
    { first: 'Murat', last: 'Yıldırım' },
    { first: 'Oluwaseun', last: 'Afolayan' },
    { first: 'Zehra', last: 'Kaya' },
    { first: 'Kwesi', last: 'Acheampong' },
    { first: 'Yanique', last: 'Rodriguez' },
    { first: 'Chidiebere', last: 'Okorie' },
    { first: 'Ayşe', last: 'Özcan' },
    { first: 'Oluwadamilare', last: 'Ogunbiyi' },
    { first: 'Shevon', last: 'James' },
    { first: 'Burak', last: 'Demir' },
    { first: 'Folasade', last: 'Adeyemo' },
    { first: 'Machel', last: 'Brown' },
    { first: 'Ayodeji', last: 'Oluwole' },
    { first: 'Elif', last: 'Yıldız' },
    { first: 'Kwame', last: 'Owusu' },
    { first: 'Esmeralda', last: 'Fernandez' },
    { first: 'Chinedu', last: 'Nnamani' },
    { first: 'Selin', last: 'Çetin' },
    { first: 'Oluwaseyi', last: 'Oladele' },
    { first: 'Shaniqua', last: 'Bacchus' },
    { first: 'Emre', last: 'Aydın' },
    { first: 'Folake', last: 'Akinwande' },
    { first: 'Usain', last: 'Charles' },
    { first: 'Adeola', last: 'Eze' },
    { first: 'Gizem', last: 'Yılmaz' },
    { first: 'Kwabena', last: 'Asante' },
    { first: 'Xiomara', last: 'Perez' },
    { first: 'Chukwuemeka', last: 'Okonkwo' },
    { first: 'Merve', last: 'Özdemir' },
    { first: 'Oluwadamilola', last: 'Adebisi' },
    { first: 'Shanique', last: 'Ramsammy' },
    { first: 'Mustafa', last: 'Kara' },
    { first: 'Folasade', last: 'Oladipo' },
    { first: 'Delroy', last: 'Martinez' },
    { first: 'Aisha', last: 'Yıldırım' },
    { first: 'Oluwaseun', last: 'Olawale' },
    { first: 'Zeynep', last: 'Çelik' },
    { first: 'Kwesi', last: 'Mensah' },
    { first: 'Yaritza', last: 'Hernandez' },
    { first: 'Chidi', last: 'Adeniyi' },
    { first: 'Esra', last: 'Özcan' },
    { first: 'Olumide', last: 'Ogunleye' },
    { first: 'Shevonne', last: 'Thompson' },
    { first: 'Cem', last: 'Demir' },
    { first: 'Folake', last: 'Adegoke' },
    { first: 'Machel', last: 'Edwards' },
    { first: 'Adekunle', last: 'Olatunji' },
    { first: 'Seda', last: 'Yıldız' },
    { first: 'Kwame', last: 'Boateng' },
    { first: 'Yanique', last: 'Gomez' },
    { first: 'Chukwudi', last: 'Nwosu' },
    { first: 'Yasemin', last: 'Aydın' },
    { first: 'Oluwadamilare', last: 'Afolayan' },
    { first: 'Shantel', last: 'Persaud' },
    { first: 'Murat', last: 'Özdemir' },
    { first: 'Oluwaseyi', last: 'Adeyemi' },
    { first: 'Zehra', last: 'Kaya' },
    { first: 'Kwesi', last: 'Acheampong' },
    { first: 'Esmeralda', last: 'Rodriguez' },
    { first: 'Chidiebere', last: 'Okorie' },
    { first: 'Ayşe', last: 'Çetin' },
    { first: 'Oluwaseun', last: 'Ogunbiyi' },
    { first: 'Shevon', last: 'James' },
    { first: 'Burak', last: 'Yılmaz' },
    { first: 'Folasade', last: 'Adeyemo' },
    { first: 'Usain', last: 'Brown' },
    { first: 'Ayodeji', last: 'Oluwole' },
    { first: 'Elif', last: 'Özcan' },
    { first: 'Kwabena', last: 'Owusu' },
    { first: 'Xiomara', last: 'Fernandez' },
    { first: 'Chinedu', last: 'Nnamani' },
    { first: 'Selin', last: 'Kara' },
    { first: 'Oluwadamilola', last: 'Oladele' },
    { first: 'Shaniqua', last: 'Bacchus' },
    { first: 'Emre', last: 'Yıldırım' },
    { first: 'Folake', last: 'Akinwande' },
    { first: 'Machel', last: 'Charles' },
    { first: 'Adeola', last: 'Eze' },
    { first: 'Gizem', last: 'Demir' },
    { first: 'Kwame', last: 'Asante' },
    { first: 'Yanique', last: 'Perez' },
    { first: 'Chukwuemeka', last: 'Okonkwo' },
    { first: 'Merve', last: 'Aydın' },
    { first: 'Oluwaseyi', last: 'Adebisi' },
    { first: 'Shanique', last: 'Ramsammy' },
    { first: 'Mustafa', last: 'Özdemir' },
    { first: 'Folasade', last: 'Oladipo' },
    { first: 'Delroy', last: 'Martinez' },
    { first: 'Aisha', last: 'Çelik' },
    { first: 'Oluwadamilare', last: 'Olawale' },
    { first: 'Zeynep', last: 'Yıldız' },
    { first: 'Kwesi', last: 'Mensah' },
    { first: 'Yaritza', last: 'Hernandez' },
    { first: 'Chidi', last: 'Adeniyi' },
    { first: 'Esra', last: 'Kaya' },
    { first: 'Olumide', last: 'Ogunleye' },
    { first: 'Shevonne', last: 'Thompson' },
    { first: 'Cem', last: 'Özcan' },
    { first: 'Folake', last: 'Adegoke' },
    { first: 'Usain', last: 'Edwards' },
    { first: 'Adekunle', last: 'Olatunji' },
    { first: 'Seda', last: 'Yılmaz' },
    { first: 'Kwabena', last: 'Boateng' },
    { first: 'Xiomara', last: 'Gomez' },
    { first: 'Chukwudi', last: 'Nwosu' },
    { first: 'Yasemin', last: 'Demir' },
    { first: 'Oluwaseun', last: 'Afolayan' },
    { first: 'Shantel', last: 'Persaud' },
    { first: 'Murat', last: 'Çetin' },
    { first: 'Oluwadamilola', last: 'Adeyemi' },
  ];

  const colleges = [
    'Natural Sciences', 
    'Physical Sciences', 
    'Engineering', 
    'Computer Science', 
    'Biology', 
    'Mathematics'
  ];

  const majors = [
    'Chemistry', 
    'Physics', 
    'Biology', 
    'Computer Science', 
    'Environmental Sciences', 
    'Psychology', 
    'Mathematics', 
    'Neuroscience'
  ];

  const classifications = ['Freshman', 'Sophomore', 'Junior', 'Senior'];
  const statuses = ['None sent', 'Interviewed', 'Sent', 'Pending'];
  
  const nameCount = new Map();

  // Find a name that hasn't exceeded 3 occurrences
  let scientist;
  for (let attempt = 0; attempt < scientistNames.length; attempt++) {
    scientist = scientistNames[(index + attempt) % scientistNames.length];
    const fullName = `${scientist.first} ${scientist.last}`;
    const currentCount = nameCount.get(fullName) || 0;
    
    if (currentCount < 3) {  // Change this number to limit occurrences
      nameCount.set(fullName, currentCount + 1);
      break;
    }
  }
  
  return {
    first: scientist.first,
    last: scientist.last,
    id: `STU${String(index).padStart(5, '0')}`,
    status: statuses[index % statuses.length],
    major: majors[index % majors.length],
    college: colleges[index % colleges.length],
    classification: classifications[index % classifications.length],
    email: `${scientist.first.toLowerCase()}${scientist.last.toLowerCase()}${index + 1}@my.tnstate.edu`
  };
});

// Function to display students in the table
function displayStudents(studentList) {
  const studentListElement = document.getElementById('studentList');
  studentListElement.innerHTML = ''; // Clear previous results

  studentList.forEach((student) => {
    const row = document.createElement('tr');
    row.innerHTML = `
      <td>${student.first} ${student.last}</td>  
      <td>${student.id}</td>  
      <td>${student.status}</td>  
      <td>${student.major}</td>
      <td>${student.college}</td>
      <td>${student.classification}</td> 
      <td>${student.email}</td>     
    `;
    studentListElement.appendChild(row);
  });
}

// Function to filter students based on search input
function filterStudents() {
  const searchInput = document
    .getElementById('searchInput')
    .value.toLowerCase();
  const filteredStudents = students.filter((student) => {
    return (
      `${student.first} ${student.last}`.toLowerCase().includes(searchInput) ||
      student.id.toLowerCase().includes(searchInput) ||
      (student.college && student.college.toLowerCase().includes(searchInput)) // Partial college name match
    );
  });
  displayStudents(filteredStudents);
}

// Event listener for the search button
document
  .getElementById('searchButton')
  .addEventListener('click', filterStudents);

// Initial display of all students
displayStudents(students);


